# Generated by Django 3.2.6 on 2021-08-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushrutaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(default='', max_length=50)),
                ('Users_D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sushrutaapp.users')),
            ],
        ),
    ]
