# Generated by Django 3.2.6 on 2021-08-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushrutaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='Users_P',
            new_name='user_patient',
        ),
        migrations.AddField(
            model_name='case',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='case',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='is_treated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='prescription',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AddField(
            model_name='case',
            name='user_doctor_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sushrutaapp.doctor_data'),
        ),
        migrations.AddField(
            model_name='case',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
