# Generated by Django 3.2 on 2021-08-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushrutaapp', '0002_auto_20210815_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_meeting',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
