# Generated by Django 3.2.6 on 2021-08-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushrutaapp', '0002_doctor_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symtoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
