# Generated by Django 3.2.6 on 2021-08-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sushrutaapp', '0004_rename_symtoms_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_data',
            name='isVerifired',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users_P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sushrutaapp.users')),
            ],
        ),
    ]
